# -*- coding: utf-8 -*-
"""miTask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iw7SFZxT2mGkai_pukeeKhVEsMCJ3tQa
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

df=pd.read_csv("/content/marketing_campaign.csv",sep="\t")
# pd.set_option('display.max_columns',85)
# pd.set_option('display.max_rows',85)

df.head()

import csv

newDf=df[['Income','Recency']]
plots=csv.reader(newDf)
# print(plots)

x=[]
y=[]

with open("/content/marketing_campaign.csv",'r') as csvfile:
    plots = csv.reader(csvfile, delimiter = '\t')
    i=0
    for row in plots:
            i=i+1
            x.append(row[4])
            y.append(row[8])
           

print(x)
print(y)

x.pop(0)
y.pop(0)
# x.pop(0)
# y.pop(0)
# y.pop(0)
# y.pop(0)
print(x)
print(y)
print(len(x))
print(len(y))
plt.scatter(x,y)
plt.show()

# as the income increases the recent buy also increases linearly

import seaborn as sns

print((x))
print((y))

x21=[[x1,y1] for x1 in x for y1 in y if(x1!='' and y1!='')]
kmeans=KMeans(2)
kmeans.fit(x21)

x0=[val[0] for val in x21]
x1=[val[1] for val in x21]
sns.scatterplot(x0,x1,style=kmeans.labels_,hue=kmeans.labels_)



# plt.scatter(x,model1)

